remote_theme: atomsrivet/plainwhite-jekyll
plugins:
- jekyll-remote-theme 
- jekyll-sitemap

title: Tsvetomira Dumbalska
author: Tsvetomira Dumbalska
email: tsvetomira.dumbalska@psy.ox.ac.uk
description: > # this means to ignore newlines until "show_exerpts:"
  Postdoctoral Research Fellow, Department of Experimental Psychology, University of Oxford 
show_excerpts: true # set to true to show excerpts on the homepage


plainwhite:
  name: Tsvetomira Dumbalska
  tagline: <center> Cognitive scientist <br>
   <a href="https://www.psy.ox.ac.uk/people/tsvetomira-dumbalska">Department of Experimental Psychology</a><br>
   <a href="https://www.bnc.ox.ac.uk/about-brasenose/academic-staff/628-dr-tsvetomira-dumbalska">Brasenose College</a><br>
   University of Oxford</center>
  date_format: "%b %-d, %Y"
  sitemap: true
  dark_mode: true
  social_links:
    email: tsvetomira.dumbalska@psy.ox.ac.uk
    osf: cnjr5
    orcid: 0000-0002-5761-8536
    github:  tsvetomira-dumbalska

  portfolio_image:  "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)

  